name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install libgtest
      # run: sudo apt install -y libcppunit-dev
      run: sudo apt-get install -y libgtest-dev
    - name: install libgmock
      run: sudo apt-get install -y libgmock-dev
    
    - name: configure
      run: ./configure
      
    - name: Install dependencies
      run: make
      
    - name: Run check
      run: make check
      
    - name: Run distcheck
      run: make distcheck
